User = "yutfut"
Dbname = "yutfut"
Password = "yutfut"
Host = "db"
Port = 5432
testis = "http://146.185.208.233:8080/check_solution?api_key=secret_key_here"
ml = "http://ml:9000/ml/get_similar"
ml_rec = "http://ml:9000/ml/user_heuristic"
ml_cold_start = "http://ml:9000/ml/cold_start"
cg = "http://vpn:9001/cg/fix_wa"